baseURL: https://marczen.com/ 
languageCode: ko-kr
title: marc zen의 블로그
theme: 'PaperMod'
params:
  label: 
    icon: '/img/marczen-logo.jpg'
    iconHeight: 35
  homeInfoParams:
    Title: 안녕하세요! 👋
    Content: >

      - 제 이름은 강병준이고, 서울에 거주중이며 현재 성균관대학교 심리학과를 다니면서 사업을 준비하고 있습니다.
     
      -

      - 🥅 **나의 사명** (2022.08)

      1. 끝없는 배움과 생각을 통해 이 시대의 뛰어난 사람이 되어

      2. 나만의 확고한 의미와 시야를 갖추고

      3. 그것을 _실행하고 만듦으로써_

      4. 내가 만들어낼 수 있는 _가장 큰 결과_를 만들어내며,

      5. 주변 사람에게 아낌없이 사랑하고 주는 것이다. 
      
      - 🛠 **나의 툴**

        - _풀스택 웹 개발_ (JavaScript, Node, React.js, Svelte, Sveltekit, Express.js, MongoDB, HTML, CSS, Tailwind CSS, Firebase, Firestore, Vercel, Netlify)
        - _UI/UX 디자인 & 프로토타이핑_ (figma)
        - _스타트업과 PM_
        - _음악 프로듀싱_ (Ableton Live)

      -

      - 💪 **경력**

        - jungl 스타트업 창업 및 1년간 운영 (프론트엔드 개발, UI/UX 디자인 및 PM)
        - 음악 프로듀서(taiji)로 한국 top 100 차트 인 (지니, 벅스 등) [노래듣기](https://www.melon.com/song/detail.htm?songId=32743111)
        - product hunt 릴리즈 및 풀스택 웹 개발 & UI/UX 디자인 프로젝트 다수
   
      -
 
      - 👨‍💻 **현재 무엇을 하고 있나요?**

      - ML/AI 공부 중 (자연어 처리가 주 관심사)
        
      -
 
      - 👨🏻‍🔬 **현재 내가 부족한 부분들 (노력 중)**

      - 마인드셋 관리하기

      - 세상에 부딛치는 것에 대한 거부감 (이 거부감을 나의 미터기로 이용해, "거부감이 들수록 지금 중요한 것"으로 판단하게 됨)

      - 나의 사상과 생각을 전달하기

      - 나와 같이 큰 꿈을 꾸는 팀원

      - 다른 사람에게 "무엇을 전달해줄 수 있는가"라는 질문 잊지 않기

      - AI/ML에 관련된 멘토 부재


    ShowPostNavLinks: true
    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
assets:
  favicon: "/static/favicon/favicon.ico"
  favicon16x16:  "static/favicon/favicon-16x16.png"
  favicon32x32:  "static/favicon/favicon-32x32.png"
  apple_touch_icon:  "static/favicon/apple-touch-icon.png"
  # safari_pinned_tab:  "<link / absolute url>"